spring.application.name=whereIsThat
spring.datasource.url=jdbc:mysql://localhost:3306/taskify
spring.datasource.username=root
spring.datasource.password=Pablo.2007
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
